spring:
  application:
    name: auth
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: mymysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    generate-ddl: true
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://172.16.6.79:5432/user?characterEncoding=UTF-8
#    username: postgres
#    password: popost
